language: r
warnings_are_errors: true
sudo: false

addons:
    apt:
        packages:
            - libgeos-dev
# NOTE: libgeo++-dev not on current travis-ci white list for container-based

matrix:
    include:
        - r: oldrel
          os: linux
          dist: trusty # 14.04
        - r: release
          os: linux
          dist: trusty
          env: R_CODECOV=true
        - r: devel
          os: linux
          dist: trusty
        - r: oldrel
          os: osx
        - r: release
          os: osx
          #- r: devel
          #os: osx

notifications:
  email:
    on_success: change
    on_failure: change

r_github_packages:
      - jimhester/covr

after_success:
      - Rscript -e 'covr::codecov()'
